version: "3.9"
services:
  php:
    image: php:7.0-fpm
    volumes:
      - ./app:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [php]
